### PR TITLE
Spike: arg transformations

### PR DESCRIPTION
**Pull request by drewburlingame**
@bilal-fazlani  this one needs your review.  

This introduces a new design choice aimed to make it easier for us to compose parsing behavior.  We'll be able to introduce .rsp file support very easily with this.  
When we fill confident with the API, we can expose it to devs to extend the parsing behavior.  
We can use this pattern to introduce the middleware concept as a great way to introduce new optional features and provide greater extensibility.

This also gives us more information from the `[parse]` command.  I found it useful while debugging tests.  I just added `[parse]` and saw the bug in the test output.  No need to step into the debugger.

This also fixes our parsing errors from #59 and so you can disregard the other branch if we merge this one.

I'm eager to hear your thoughts.

### CODE REVIEW

**Comment by drewburlingame** [comment]
With the argument fix, we can release a new version without the beta tag.

**Comment by bilal-fazlani** [comment]
Ok, please help me get some deeper understanding.

I see that in this PR, user has to pass “[parse]” as as an argument so that app shows how all arguments and options are parsed. This is just for debugging purpose and does not actually execute any user logic, Right?

The idea seems cool. I have some questions on this.

1. What can be examples of 
> We can use this pattern to introduce the middleware concept as a great way to introduce new optional features and provide greater extensibility. 

2. Why does the user has to pass this thing as an argument? Could it not be something like :

 ```c#
new AppRunner<MyApp>()
    .Parse(args )
```

Or maybe `.Parse(args).Run(args)` if they want to parse and run

3. What is a .rsp file?
> We'll be able to introduce .rsp file support very easily with this.

**Comment by drewburlingame** [comment]
I'll answer in reverse order...

3. Simplest to let someone else explain it.

* https://docs.microsoft.com/en-us/visualstudio/msbuild/msbuild-response-files?view=vs-2019 
* https://github.com/dotnet/command-line-api/wiki/Features-overview#response-files

I've used this concept in the past.  It's a handy way to store common option sets and to let apps pass options to other apps.

2. This PR doesn't introduce the `[parse]` directive.  `[parse]` & `[debug]` were already added.  I used `[parse]` because it was already introduced by [System.CommandLine docs](https://github.com/dotnet/command-line-api/wiki/Features-overview#parse-preview).  It's purpose is to help the user of the console understand how their values were parsed, to log how the input was parsed.  Like an advanced echo command.   If `[parse]` is passed in, then no user logic is executed.

3. Examples of middleware

``` c#
new AppRunner<MyApp>()
   .UseRspFiles()
   .AddArgumentTransformation( TaorisApp.MergeArguments )
   .UseMiddleware( DrewsApp.InjectArgModelsIntoContainers )
```

Middleware is the pipeline you suggested be implemented instead of the ICommandInvoker.  My org didn't have budget to implement the Middleware concept so we went with the easier-to-implement Decorator pattern.

**Comment by bilal-fazlani** [comment]
- Ohh yeah, the middlewares. I remember now. Sounds good to me 👍 

- RSP seems cool and very useful. 👍 

- about the `parse` thing, being able to view how arguments are parsed sounds good. However I have not seen any CLI tool that has exposed this feature to their end user. Have you seen anything like that?
Especially anything in the form of square brackets.. (`[bla bla]`).
If you have strong opinions/reasons about it, go ahead.

On a sidenote, the dotnet CommandLine thing seems good. Especially what they are doing with DragonFruit.

**Comment by drewburlingame** [comment]
Great, sounds like we're on the same page.  I haven't seen the directives concept before.  I think CommandLine introduced it.  Since I've implemented this pretty much everywhere and I know I'll use and socialize it with my companies, it would be very useful to me to have it built in. 

I agree, I think DragonFruit could be great.  I've been thinking that after I finish a couple more updates I'll look at helping out with that or merging these two projects by forking theirs and introducing the constructs we have.

**Comment by drewburlingame** [comment]
I updated the parsing logic, adding a Tokenizer so arg transformations and parsing logic would be cleaner overall.  I also separated parsing logic from execution, finally getting the cyclomatic complexity of the parsing logic below the 100% threshold.  It's still ugly, but I think the control flow is a little more clear. 

I also disabled directives by default and added an AppSettings.EnableDirectives.  This way we don't accidentally break existing scripts.

**Pull request merged**
