### PR TITLE
add Release Notes to documentation

### PR DESCRIPTION
**Pull request by drewburlingame**

### CODE REVIEW

**Comment by drewburlingame** [comment]
@bilal-fazlani what do you think of this structure for release notes?  one page per project.  I was thinking the roadmap could serve as a guide for devs on what can change but more effectively as a reminder for us.  We can collect the updates here.

**Comment by bilal-fazlani** [comment]
nice. netlify makes it very to see to visualise change
https://deploy-preview-230--commanddotnet.netlify.com

I love what you have done with release notes!

**Comment by bilal-fazlani** [comment]
I just pushed another commit to use tabs for release notes and roadmap to bring it up on top. See if you like it.

**Comment by bilal-fazlani** [comment]
The contents of change logs are very detailed. It is really awesome.

**Pull request merged**
