### PR TITLE
Hooks

### PR DESCRIPTION
**Pull request by drewburlingame**
@bilal-fazlani here's a spike of implementing pre & post-hooks functionality for design review.  I think this would solve #55 for the most part.  All hook params have to be IArgumentModel.  I'm not familiar enough with the internal mapping code to support more than that.

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
Thanks @drewburlingame for all the effort you are making on this library. I will take a look at these during the weekend

**Comment by drewburlingame** [comment]
I need to reread the docs.  I didn't digest what Inherited did the first time through.  I'll be using that a lot more.  And it makes the pre & post hook seem mostly unnecessary.  The reason a pre hook may still be useful is to prevent throwing exceptions in the ctor.  But, as long as the library returns the real exception instead of the TypeInitializationException, I don't think there's a need for these hooks at all.

**Comment by bilal-fazlani** [comment]
This is my fault. I dont think I have done a good job documenting 'Inherited' enough and with examples. I will do that.

**Comment by drewburlingame** [comment]
I think there's just a lot to take in.  Examples would be helpful.  Now that you have ctor & dispose, it would be helpful to call out that pattern.

**Pull request closed without merging**
