### PR TITLE
offer context based alternatives for miss typed arguments

### PR DESCRIPTION
**Pull request by drewburlingame**
implements #41

### CODE REVIEW

**Comment by drewburlingame** [comment]
@bilal-fazlani this is the start of #41.  It just needs the filtering to limit the commands and options.  this could possibly serve as an mvp

**Comment by drewburlingame** [comment]
needs docs & tests

**Comment by bilal-fazlani** [comment]
How are we calculating `The most similar command` or `option` ?

**Comment by drewburlingame** [comment]
It needs that still.  I was setting it up for you :) :) 

I added a some options and was testing them with the sample app.  Sometimes one seems better than the other.  There's probably other algos I'm not familiar with.

**Comment by bilal-fazlani** [comment]
👍  Nice.

**Comment by drewburlingame** [comment]
@bilal-fazlani can you give this a review?  see tests and documentation for examples.

**Comment by bilal-fazlani** [comment]
https://deploy-preview-203--commanddotnet.netlify.com/Middleware/typo-suggestions/
Nice!

**Comment by bilal-fazlani** [comment]
Ok. Sure. Will take a look at tests as well

**Comment by drewburlingame** [comment]
ps, if you merge this, please `Squash and merge`.

**Comment by bilal-fazlani** [comment]
I tried some commands and options just to see how it works. For most cases it works as expected.

for the given string:

```
public void MyCommand([Option]String username)
{
    Console.WriteLine("done");
}
```

I was hoping it would suggest me the right name, but it didnt

input
```
dotnet run MyCommand --nameuser
```

output:
```
Unrecognized option '--nameuser'

Usage: dotnet CommandDotNet.Example.dll MyCommand [options]

Options:

  --username  <TEXT>
```

**Comment by drewburlingame** [comment]
I can see what you're hoping for. It's a much more complex algorithm.  Git wouldn't figure that out for you either.  

``` bash
~
$ git worktre
git: 'worktre' is not a git command. See 'git --help'.

The most similar command is
        worktree

~
$ git treework
git: 'treework' is not a git command. See 'git --help'.

```

**Comment by drewburlingame** [comment]
@bilal-fazlani #206 resolves what you mentioned.  It's not too complex and I don't think it's significantly more expensive since command and option names are usually short.

What I'm not sure of are the cases where this could return false positives.  I'd like to mull it over a bit longer.  I think we could merge this PR since it's ~ feature parity with git.

**Comment by bilal-fazlani** [comment]
Alright cool

**Pull request merged**
