### PR TITLE
[PR] The proj files have been updated to enable SourceLink

### PR DESCRIPTION
**Pull request by JTOne123**
CSProj files have been updated to enable SourceLink in your nuget
---

*[This pull request was created with an automated workflow]*

I noticed that your repository and Nuget package are important for our .NET community, but you still haven't enabled SourceLink.

**We have to take 2 steps:**
1) Please approve this pull request and make .NET a better place for .NET developers and their debugging.
2) **Then just upload the .snupkg file** to https://www.nuget.org/ (now you can find the snupkg file along with the .nuget file)

You can find more information about SourceLine at the following links  
https://github.com/dotnet/sourcelink
https://www.hanselman.com/blog/ExploringNETCoresSourceLinkSteppingIntoTheSourceCodeOfNuGetPackagesYouDontOwn.aspx

If you are interesting about this automated workflow and how it works  
https://github.com/JTOne123/GitHubMassUpdater

*If you notice any flaws, please comment and I will try to make fixes manually*

### CODE REVIEW

**Comment by drewburlingame** [comment]
Hi @JTOne123, thanks for posting this.  Looks like an interesting tool.

We're currently embedding the sources and managing these settings in the [Directory.Build.props](https://github.com/bilal-fazlani/commanddotnet/blob/master/Directory.Build.props) file. 

I like the idea of this better as it will reduce the size of the published package.  

If we were to take this on, the PR would need to change the props files instead of the proj files and it would need to include updated build to publish the snupkg file so we didn't lose any functionality.

**Comment by JTOne123** [comment]
agree

**Comment by drewburlingame** [comment]
another reference for future: https://www.meziantou.net/how-to-debug-nuget-packages-using-sourcelink.htm

**Comment by drewburlingame** [comment]
@JTOne123 do you plan to update your tool to check for & modify Directory.Build.props files and then submit a new PR?  If so, I'll wait for that PR, otherwise, I'll create a new PR with the updates in the new file and remain grateful for your nudge in this direction.

**Comment by JTOne123** [comment]
yes, please create new PR

I don't plan to update Directory.Build.props for now

so, I just close this PR

**Pull request closed without merging**
