### PR TITLE
CommandDotNet.TestTools

### PR DESCRIPTION
**Pull request by drewburlingame**
@bilal-fazlani  I extracted the testing tools into a separate project because I would like to use them in other projects.  It's handy to be able to test at the API level like this.  It will also help when building middleware in other projects.

The only thing missing from this is the update to our build process that would allow us to publish targetted NuGet packages based on the project-specific tags, as discussed in #154.  I'll merge this without that and we can advantage of it when we get to it.  The build process is the part I'm least familiar with so if you were able to update that in the next week or two, I would do the work of creating the other 3rd party projects in the repo.  And no worries if you don't have the time.  I'll figure it out.

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
I will take a look a t build process today. I will have to update `deploy.sh` and `.travis .yml`. This should not be a big, I guess.

Just to make sure I am on the same page - this is what we are looking at..

This repo will contain multiple projects.

image

Every time we make a commit, the build runs usually compiling everything and running tests for the entire solution.

But when there is a tag present which is of format `project1_2.4.3-beta`, in addition to compile and test, we also want to runt the deployment stage of the pipeline for that project. 

Is this understanding correct?

**Comment by bilal-fazlani** [comment]
Also, my understanding is that if 'project2' needs 'project1' it will have to depend on nuget package of 'project1' and can't directly have a project dependency. What do you think?

**Comment by bilal-fazlani** [comment]
Deployment scripts updated. Now to deploy a new version we need to provide tag in new format. 

PeojectName_Version

**Comment by bilal-fazlani** [comment]
I am thinking this should allow us to bring the 2 DI repositories in this repo under the same solution... I am gonna try that today

**Comment by drewburlingame** [comment]
Hi @bilal-fazlani.  I'm sorry I couldn't reply sooner.  I was away from tech for the weekend.

Yes, that's the pattern I was thinking.  And yes, we can bring the DI projects into this repo.

**Comment by drewburlingame** [comment]
@bilal-fazlani Just looking at the updates you pushed to master.  This... is... FANTASTIC!.  Thank you.  I'll merge those into the beta_v3/master branch and then update the PRs

**Pull request merged**
