### PR TITLE
Providing common behavior to wrap execution of a command #50

### PR DESCRIPTION
**Pull request by al322se**

### CODE REVIEW

**Comment by bilal-fazlani** [comment]
I have gone through this PR for issue #50 and after thinking a lot I feel that this feature and the way it's implemented is not going to be very useful for most of the other users. In the interest if keeping this framework simple and generic, I can't merge this PR. But you are free to raise another PR to mark things virtual so that you can override methods to achieve your goal.

**Comment by al322se** [comment]
Sorry, could you please explain, what do you mean? Do you mean make RunCommand method of CommandRunner virtual?

**Comment by drewburlingame** [comment]
I understand your point on keeping the framework simple for users.  I wouldn't want to change that.  I have an idea below for making it simpler.

As for the usefulness for others, I think there are more ways this feature could be beneficial.  For example, I created  [this tool](https://github.com/drewburlingame/GitTools/tree/master/BbGit) a few months ago and would have used it there too.  I have common arguments across commands that are used to initialize other operations.  I could have injected piped inputs with a convention in the parameter declaration.  I also think other enterprises would want similar behavior to reduce boilerplate and reduce risks of devs missing critical steps.

You mentioned marking things as virtual.  What would you mark as virtual?  The point we need to intercept is the method invocation.   We need CommandRunner.RunCommand to perform all of the logic before the invocation.

An alternative could be to create an interface with a default implementation, like this

```
        public interface ICommandMethodInvoker
        {
            object Invoke(CommandInfo commandInfo, object instance, object[] parameterValues);
        }

        internal class DefaultCommandMethodInvoker: ICommandMethodInvoker
        {
            public object Invoke(CommandInfo commandInfo, object instance, object[] parameterValues)
            {
                MethodInfo theMethod = instance.GetType().GetMethod(commandInfo.MethodName);
                return theMethod?.Invoke(instance, parameterValues);
            }
        }
```

the DefaultCommandMethodInvoker can be overwritten in the AppRunner where you suggested the other be handled.  In our case, we could create a decorator to wrap this, like `appRunner.CommandMethodInvoker = new OurConsoleCommandMethodInvoker(appRunner.CommandMethodInvoker)`

It's still simple in the framework.  The only new thing exposed is the property on AppRunner and we've removed the IF statement.  

Passing in the command info gives us a way to interrogate the attributes of the method.

**Comment by drewburlingame** [comment]
Or, we could go with your suggestion of `OnBeforeExecute` and register the event.  The Before step is the most critical for us.  As i think about it more, any exceptions that escape the execution can be caught in an exception handler around appRunner.Run.  Would that work for you?

**Comment by drewburlingame** [comment]
While I do think of it as a setting, I don't have an attachment to either location.  We'll put the event on AppRunner.  If we need more down the road, we'll discuss it then.  Thanks for the feedback.  As someone who'll be using the framework, I appreciate that you're push back to keep it simple.

**Comment by drewburlingame** [comment]
It looks good, except we need the `object[] mergedParameters` instead of `List<ArgumentInfo> parameterValues` so we can have the final IArgumentModel.

An additional question.  I noticed the event handler lives in AppSettings but is internal.  What rule do you use for when something is an internal vs public app setting?  Without understanding your thoughts, it seems simpler and more discoverable to make it public on AppSettings.

**Comment by bilal-fazlani** [comment]
> It looks good, except we need the object[] mergedParameters instead of List<ArgumentInfo> parameterValues so we can have the final IArgumentModel.

yeah. I just played around with the code to see if it's possible to use events. You can include those merged parameters.

> An additional question. I noticed the event handler lives in AppSettings but is internal. What rule do you use for when something is an internal vs public app setting? Without understanding your thoughts, it seems simpler and more discoverable to make it public on AppSettings.

So AppSettings contain some public and some internal properties. public properties are the ones that I am accepting from the user directly using the AppSettings object. These are simple configuration values such as strings, booleans, enums etc.

There are some other settings that are custom implementations (behaviours). For example. 

```
internal IHelpProvider CustomHelpProvider { get; set; }
```

Although it's present in AppSettings users can't provide it directly. These are some advanced settings and I didn't want users to see these settings unless they really explicitly want to set these settings. 

So if someone want to use their own HelpProvider, they will have to extend from IHelpProvider and create their own class and then pass an instance as shown below:

```C#
    AppRunner<MyApplication> appRunner = new AppRunner<MyApplication>(
    new AppSettings{
        Case = Case.CamelCase,
        EnableVersionOption = true
    })
    .WithCustomHelpProvider(new MyCustomHelpProvider());
```

All these things ultimately reside in AppSettings only as AppSettings is flowing down the chain of method executions.

Since what we want to pass is also a behaviour or a custom implementation, I thought it would be consistent with existing design if we don't use AppSettings directly.

If we don't use events and follow the same conventions, we might have something like:

```C#
            AppRunner<MyApplication> appRunner = new AppRunner<MyApplication>(
                new AppSettings{
                    Case = Case.CamelCase,
                    EnableVersionOption = true
                })
                .WithCustomHelpProvider(new MyCustomHelpProvider())
                .WithCommandInterceptor(new MyCustomCommandInterceptor());
```

Does this make sense? Or have I made it more complicated?

**Comment by bilal-fazlani** [comment]
FYI I don't have a very string opinion about keeping things internal in AppSettings. If you think it makes it transparent and simple, go ahead and make it public. Also, if we use AppSettings directly, then event does not make sense. Then we should have an interface. We just have to decide if we want ICommandInvoker or ICommandInterceptor. I think ICommandInterceptor is safe.

**Comment by drewburlingame** [comment]
I better understand what you're thinking about for AppSettings.   Providing a custom behavior is different than say, toggling a bool.  Considering those advanced settings makes sense.  For overriding behaviors, assigning the interface to a property or method on the AppRunner makes sense.  You've also got documentation to fall back on so discoverability is not such a problem.

I like the interceptor idea.  This is an example of using a DynamicProxy interceptor.  

``` c#
    public void Intercept(IInvocation invocation)
    {
        invocation.Proceed();
        if (invocation.ReturnValue == invocation.InvocationTarget)
        {
            invocation.ReturnValue = invocation.Proxy;
        }
    }
```

Notice that `invocation.Proceed()` is used to execute the invocation.  This allows the interceptor to determine when to execute.  It allows for any level of complexity and so it's very extensible.  We can add logging, metrics, generic failure recovery, etc.

Here are my thoughts:

We could follow an interceptor pattern by:
- create ICommandInterceptor with a default pass-through implementation and assign it to the AppRunner.
- create a CommandInterceptorInvocation object to pass into Intercept.
  - contains the CommandInfo, merged params & list of arg infos.  
  - defines a Proceed() method devs will call in their interceptors
    - If logging was added, we could log a warn level log if the Proceed method wasn't called.  It would be useful to add LibLog at some point to help with this kind of debugging.
  - this parameter object also allows you to add properties later without breaking the interface of the Intercept method.
- documenting the usage
- create the dispatcher.  this is where we add complexity to the solution to reduce complexity for the developer.

A simpler version would be to use the decorator pattern by:
- create ICommandDecorator w/ CommandInvocation parameter object.  (names can be changed).  Decorator would infer this is following the decorator pattern which includes delegating requests to the inner instance
  - the default implementation will invoke the method.
  - CommandInvocation will not contain the Proceed method.
- registering the decorator with `.WithCommandDecorator(inner => new MyCommandDecorator(inner));`
- create documentation.  Decorator is a common pattern so documentation can be simple examples.

I don't see much trade-off to use the second option and it's simpler code to write & maintain.  That would be my recommendation.  What do you think?

**Comment by drewburlingame** [comment]
That's correct.  We'll work it up for you.

**Comment by drewburlingame** [comment]
@bilal-fazlani After reviewing again and discussing with others, we thought CommandInvoker was a better name because it described the intent of the class, not an intended pattern.  By providing Instance on CommandInvocation, users can completely override how the method is invoked, or they can implement the decorator pattern.  A new PR has been created https://github.com/bilal-fazlani/commanddotnet/pull/52

**Comment by bilal-fazlani** [comment]
Thanks @drewburlingame  . I will take a look at the new PR. I will close this PR .

**Pull request closed without merging**
